// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file chat.proto (package chat.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { BroadcastChatRequest, BroadcastChatResponse, NewChatSessionRequest, NewChatSessionResponse } from "./chat_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chat.v1.ChatService
 */
export const ChatService = {
  typeName: "chat.v1.ChatService",
  methods: {
    /**
     * @generated from rpc chat.v1.ChatService.NewChatSession
     */
    newChatSession: {
      name: "NewChatSession",
      I: NewChatSessionRequest,
      O: NewChatSessionResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc chat.v1.ChatService.BroadcastChat
     */
    broadcastChat: {
      name: "BroadcastChat",
      I: BroadcastChatRequest,
      O: BroadcastChatResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

